#!/usr/bin/env python3
"""
Demo script showing how to use the GlassThemeSystem.
This demonstrates the basic usage and CSS generation capabilities.
"""

from pyservx.glass_theme_system import GlassThemeSystem, ThemeConfig, ColorPalette


def main():
    """Demonstrate GlassThemeSystem usage."""
    
    print("=" * 70)
    print("GlassThemeSystem Demo - Apple iOS Glass Theme")
    print("=" * 70)
    print()
    
    # 1. Create a default glass theme system
    print("1. Creating default GlassThemeSystem...")
    theme = GlassThemeSystem()
    print("   ✓ Default theme created successfully")
    print()
    
    # 2. Generate CSS variables
    print("2. Generating CSS custom properties...")
    css_vars = theme.generate_css_variables()
    print(css_vars)
    print()
    
    # 3. Apply glass effect to different components
    print("3. Applying glass effects to components...")
    print()
    
    print("   Panel Component:")
    panel_styles = theme.apply_glass_effect("panel")
    for prop, value in panel_styles.items():
        print(f"     {prop}: {value}")
    print()
    
    print("   Button Component:")
    button_styles = theme.apply_glass_effect("button")
    for prop, value in button_styles.items():
        print(f"     {prop}: {value}")
    print()
    
    print("   Input Component:")
    input_styles = theme.apply_glass_effect("input")
    for prop, value in input_styles.items():
        print(f"     {prop}: {value}")
    print()
    
    # 4. Generate complete CSS for components
    print("4. Generating complete CSS for glass components...")
    print()
    
    print("   Glass Panel CSS:")
    print(theme.generate_glass_panel_css())
    
    print("   Glass Button CSS:")
    print(theme.generate_glass_button_css())
    
    print("   Glass Input CSS:")
    print(theme.generate_glass_input_css())
    
    # 5. Custom configuration example
    print("5. Creating custom theme configuration...")
    custom_config = ThemeConfig(
        blur_strength=15,
        shadow_intensity=0.4,
        border_radius=16,
        animation_duration=0.4
    )
    custom_theme = GlassThemeSystem(config=custom_config)
    print(f"   ✓ Custom theme created with:")
    print(f"     - Blur strength: {custom_config.blur_strength}px")
    print(f"     - Shadow intensity: {custom_config.shadow_intensity}")
    print(f"     - Border radius: {custom_config.border_radius}px")
    print(f"     - Animation duration: {custom_config.animation_duration}s")
    print()
    
    # 6. Calculate blur radius for different screen densities
    print("6. Calculating blur radius for different screen densities...")
    print(f"   Standard (1x): {theme.calculate_blur_radius(1.0)}px")
    print(f"   Retina (2x): {theme.calculate_blur_radius(2.0)}px")
    print(f"   High DPI (3x): {theme.calculate_blur_radius(3.0)}px")
    print()
    
    # 7. Generate shadow effects
    print("7. Generating shadow effects...")
    shadow = theme.generate_shadow((0, 0), (100, 100))
    print(f"   Shadow: {shadow}")
    print()
    
    # 8. Custom color palette example
    print("8. Creating custom color palette...")
    custom_palette = ColorPalette(
        accent_green="#00cc00",
        text_primary="#00cc00"
    )
    theme.update_color_palette(custom_palette)
    print(f"   ✓ Updated accent green to: {custom_palette.accent_green}")
    print()
    
    # 9. Save complete CSS to file
    print("9. Generating complete CSS file...")
    complete_css = generate_complete_css(theme)
    
    try:
        with open("glass_theme.css", "w") as f:
            f.write(complete_css)
        print("   ✓ CSS saved to: glass_theme.css")
    except Exception as e:
        print(f"   ✗ Error saving CSS: {e}")
    
    print()
    print("=" * 70)
    print("Demo completed successfully!")
    print("=" * 70)


def generate_complete_css(theme: GlassThemeSystem) -> str:
    """
    Generate a complete CSS file with all glass theme styles.
    
    Args:
        theme: GlassThemeSystem instance
        
    Returns:
        str: Complete CSS content
    """
    css = "/* Apple iOS Glass Theme - Generated by GlassThemeSystem */\n\n"
    css += theme.generate_css_variables()
    css += "\n\n/* Glass Components */\n\n"
    css += theme.generate_glass_panel_css()
    css += "\n"
    css += theme.generate_glass_button_css()
    css += "\n"
    css += theme.generate_glass_input_css()
    css += "\n"
    
    # Add glass table styles
    css += """
/* Glass Table */
.glass-table {
  background: var(--bg-glass-secondary);
  backdrop-filter: blur(var(--blur-strength)) saturate(180%);
  -webkit-backdrop-filter: blur(var(--blur-strength)) saturate(180%);
  border-radius: var(--border-radius);
  border: 1px solid var(--border-default);
  overflow: hidden;
}

.glass-table thead {
  background: var(--interactive-default);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  color: var(--text-primary);
  border-bottom: 2px solid var(--border-default);
}

.glass-table tbody tr:hover {
  background: rgba(0, 255, 0, 0.08);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
}

.glass-table td,
.glass-table th {
  border-bottom: 1px solid rgba(0, 255, 0, 0.15);
  padding: 0.75rem;
}

/* Browser Compatibility */
@supports not (backdrop-filter: blur(20px)) {
  .glass-panel,
  .glass-button,
  .glass-input,
  .glass-table {
    background: rgba(0, 0, 0, 0.85);
  }
}

/* Hardware Acceleration */
.glass-panel,
.glass-button,
.glass-input,
.glass-table {
  transform: translateZ(0);
  will-change: backdrop-filter, transform;
}

/* Responsive Design */
@media (max-width: 768px) {
  .glass-panel,
  .glass-table {
    backdrop-filter: blur(12px) saturate(150%);
    -webkit-backdrop-filter: blur(12px) saturate(150%);
  }
  
  .glass-button {
    min-height: 44px;
    min-width: 44px;
    padding: 12px 20px;
  }
}

/* High Contrast Mode */
@media (prefers-contrast: high) {
  :root {
    --text-secondary: rgba(0, 255, 0, 0.9);
    --text-tertiary: rgba(0, 255, 0, 0.7);
    --bg-glass-primary: rgba(0, 0, 0, 0.95);
    --border-default: rgba(0, 255, 0, 0.5);
  }
  
  .glass-panel,
  .glass-button,
  .glass-input,
  .glass-table {
    backdrop-filter: none;
    -webkit-backdrop-filter: none;
  }
}
"""
    
    return css


if __name__ == "__main__":
    main()
